# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
