# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('rest_api', '0003_task_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
