# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20180429_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
